### ISSUE TITLE
please support harmattan

### ISSUE THREAD

**Issue by rzr** [berndhs/e6irc#1]
I did try to rebuild on harmattan  and it build after I fixed debian/rules ( clean should not depends on anything )

but I did not manage to start it i just fork the current displayed window are there args to pass on ?
## 

http://rzr.online.fr/q/irc

**Comment by berndhs** [comment]
still can't reproduce that, it built version 0.6.4 ok here http://repo.pub.meego.com/home:/earthling/Harmattan/armel/

**Comment by rzr** [comment]
I will try it out after my upgrade , do you want to upload to my repo too ?

**Comment by berndhs** [comment]
No more harmattan, so this is closed. Unless harmattan is revived.
